#27553: Add experimental solution for support template string
regru/eslint-plugin-regru pull request #3
Opened 2019-01-23 05:25 UTC by domoratskii

Есть предложение просто заменить тип у template_strings. Тогда не придется менять основную логику, не нужно добавлять новое исключение в конфиги eslint, где используется eslint-plugin-regru.

@podkot @shifteee

2019-01-23 06:12 UTC, shifteee reviewed
plz check something like this
```javascript
fn( anotherFn`arg` );
```

2019-01-23 06:45 UTC, shifteee commented
> Действительно данная строка проходит как валидная, но разве это в рамках eslint-plugin-regru ? Тут уже парсер eslint не справляется

Там все валидно. Вопрос в том, просит ли плагин пробелы

2019-01-23 06:54 UTC, domoratskii commented
> Там все валидно.
Пропустил этот момент, нужно изучить)

> Там все валидно. Вопрос в том, просит ли плагин пробелы
Да, если их нет - просит пробелы.

2019-01-23 08:47 UTC, domoratskii commented
Пока что не надо мержить, сейчас проверю пару моментов

2019-01-30 12:09 UTC, domoratskii commented
@podkot @shifteee review pls

2019-01-30 13:10 UTC, domoratskii commented
И еще момент, в репе нету линтера, можем занесем свой @podkot ?

2019-01-30 13:16 UTC, podkot commented
> И еще момент, в репе нету линтера, можем занесем свой @podkot ?

я за, но это сабж для отдельного мр

2019-01-30 13:17 UTC, podkot commented
oops, i've meant 'yea shure, but that is going to be a separate PR'

2019-01-30 13:57 UTC, podkot requested changes
tests pls

2019-01-31 14:16 UTC, domoratskii commented
Вроде поправил, но еще есть спорные моменты. Например с [243-323](https://github.com/regru/eslint-plugin-regru/pull/3/files#diff-8fe2d7e70af1604d722c95bcb9f847b6R243). Функция `stringOrTemplateInParenAlreadyChecked`. Как бы это лучше разбить ?

2019-02-04 15:43 UTC, podkot approved these changes

2019-02-04 15:46 UTC, podkot commented
@domoratskii 
There's a lack of edge cases in tests probably? F.e. when a line begins with a template literal?

2019-02-05 13:47 UTC, domoratskii commented
@podkot added tests. check pls

2019-02-05 14:25 UTC, merged